config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :food_intake, only: %i[index new create]
  resources :activity_level, only: %i[index new create]
  resources :recipes, only: %i[index create show]

  root to: 'dashboard#index'

  match '*not_found', to: 'errors#error404', via: %i[get post]
end

app/models/activity_level.rb
class ActivityLevel < ApplicationRecord
  belongs_to :user

  scope :todays, ->(user) { where(created_at: Time.zone.today.all_day, user: user).reverse_order }
  scope :for_date, ->(user, date) { where(created_at: date, user: user).reverse_order }

  RANGE = (1..3).freeze

  COLUMNS_TO_VALIDATE = %i[vitamin_c vitamin_d3 iron].freeze

  COLUMNS_TO_VALIDATE.each do |attr|
    validates attr,
              allow_nil: true,
              inclusion: { in: RANGE }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_intake.rb
class FoodIntake < ApplicationRecord
  belongs_to :user

  scope :todays, ->(user) { where(created_at: Time.zone.today.all_day, user: user).reverse_order }
  scope :for_date, ->(user, date) { where(created_at: date, user: user).reverse_order }

  RANGE = (4..10).freeze

  COLUMNS_TO_VALIDATE = %i[vitamin_c vitamin_d3 iron].freeze

  COLUMNS_TO_VALIDATE.each do |attr|
    validates attr,
              allow_nil: true,
              inclusion: { in: RANGE }
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  scope :todays, ->(user) { where(created_at: Time.zone.today.all_day, user: user) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :food_intakes, dependent: :destroy
  has_many :activity_levels, dependent: :destroy
  has_many :recipes, dependent: :destroy
end

app/controllers/activity_level_controller.rb
class ActivityLevelController < ApplicationController
  def index
    @activity_levels = ActivityLevel.todays(current_user)
  end

  def new
    @activity_level = ActivityLevel.new(user: current_user)
  end

  def create
    @activity_level = ActivityLevel.new(activity_level_params.merge(user: current_user))

    if @activity_level.save
      redirect_to activity_level_index_path, flash: { success: 'added activity level' }
    else
      flash.now[:error] = @activity_level.errors.full_messages.join(', ')
      render 'new'
    end
  rescue StandardError => e
    redirect_to root_path, flash: { error: e.message }
  end

  private

  def activity_level_params
    params.require(:activity_level).permit(%i[vitamin_c vitamin_d3 iron])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: %i[height weight])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  skip_before_action :authenticate_user!

  def error404
    @not_found_path = params[:not_found]
  end
end

app/controllers/food_intake_controller.rb
class FoodIntakeController < ApplicationController
  def index
    @food_intakes = FoodIntake.todays(current_user)
  end

  def new
    @food_intake = FoodIntake.new(user: current_user)
  end

  def create
    @food_intake = FoodIntake.new(food_intake_params.merge(user: current_user))

    if @food_intake.save
      redirect_to food_intake_index_path, flash: { success: 'added food intake' }
    else
      flash.now[:error] = @food_intake.errors.full_messages.join(', ')
      render 'new'
    end
  rescue StandardError => e
    redirect_to root_path, flash: { error: e.message }
  end

  private

  def food_intake_params
    params.require(:food_intake).permit(%i[vitamin_c vitamin_d3 iron])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
  end

  def create
    @recipe = RecipeService.new(user: current_user).run
  ensure
    redirect_to recipes_path, flash: { success: 'recipe was generated' }
  end

  def show
    @recipe = current_user.recipes.find(params.require(:id))

    respond_to do |format|
      format.html do
        @data = Recipe::ShowSerializer.new(@recipe).to_h.with_indifferent_access
      end
      format.json do
        render json: @recipe, serializer: Recipe::ShowSerializer
      end
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    return super if params['password']&.present?

    resource.update_without_password(params.except(:current_password))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activity_level/index.html.erb
<h1>Today's activity level</h1>
<%= link_to 'enter more', new_activity_level_path %>
<table>
  <thead>
    <tr>
      <th>Vitamin C</th>
      <th>Vitamin D3</th>
      <th>iron</th>
      <th>Created Date</th>
    </tr>
  </thead>
  <tbody>
    <% @activity_levels.each do |fi| %>
      <tr>
        <td><%= fi.vitamin_c %></td>
        <td><%= fi.vitamin_d3 %></td>
        <td><%= fi.iron %></td>
        <td><%= fi.created_at.strftime('%d/%m/%Y %H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/activity_level/new.html.erb
<h1>New Activity Level</h1>

<%= form_with model: @activity_level, url: activity_level_index_path do |f| %>
  <div class="field">
    <%= f.label :vitamin_c %><br />
    <%= f.number_field :vitamin_c, in: 1..3, step: 1 %>
  </div>

  <div class="field">
    <%= f.label :vitamin_d3 %><br />
    <%= f.number_field :vitamin_d3, in: 1..3, step: 1 %>
  </div>

  <div class="field">
    <%= f.label :iron %><br />
    <%= f.number_field :iron, in: 1..3, step: 1 %>
  </div>

  <br />

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

<%= link_to "Back", :back %>

app/views/dashboard/index.html.erb
<h1>
  Hello <%= current_user.email %>
  <%= link_to edit_user_registration_path(current_user.id) do %>
    <% if current_user.height.nil? || current_user.height.nil? %>
      privide personal info
    <% else %>
      edit
    <% end %>
  <% end %>
</h1>

app/views/food_intake/index.html.erb
<h1>Today's food intake activity</h1>
<%= link_to 'enter more', new_food_intake_path %>
<table>
  <thead>
    <tr>
      <th>Vitamin C</th>
      <th>Vitamin D3</th>
      <th>iron</th>
      <th>Created Date</th>
    </tr>
  </thead>
  <tbody>
    <% @food_intakes.each do |fi| %>
      <tr>
        <td><%= fi.vitamin_c %></td>
        <td><%= fi.vitamin_d3 %></td>
        <td><%= fi.iron %></td>
        <td><%= fi.created_at.strftime('%d/%m/%Y %H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/food_intake/new.html.erb
<h1>New Food Intake</h1>

<%= form_with model: @food_intake, url: food_intake_index_path do |f| %>
  <div class="field">
    <%= f.label :vitamin_c %><br />
    <%= f.number_field :vitamin_c, in: 4..10, step: 1 %>
  </div>

  <div class="field">
    <%= f.label :vitamin_d3 %><br />
    <%= f.number_field :vitamin_d3, in: 4..10, step: 1 %>
  </div>

  <div class="field">
    <%= f.label :iron %><br />
    <%= f.number_field :iron, in: 4..10, step: 1 %>
  </div>

  <br />

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

<%= link_to "Back", :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VitaminsCalc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type="text/css">
      ul.nav li {
        display: inline;
        margin-right: 5px;
        padding: 3px;
      }
    </style>
  </head>

  <body>
    <% if user_signed_in? %>
      <ul class='nav'>
        <li><%= link_to 'dashboard', root_path %></li>
        <li><%= link_to 'today\'s food intake', food_intake_index_path %></li>
        <li><%= link_to 'today\'s activity level', activity_level_index_path %></li>
        <li><%= link_to 'recipes', recipes_path %></li>
        <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
      </ul>
    <% end %>

    <% flash.each do |type, msg| %>
      <ul>
        <li>
          <%= msg %>
        </li>
      </ul>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Recipes History</h1>

<%= link_to 'generate totays recipe', recipes_path, method: :post %>

<table>
  <thead>
    <tr>
      <th>Vitamin C</th>
      <th>Vitamin D3</th>
      <th>iron</th>
      <th>Created Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |fi| %>
      <tr>
        <td><%= fi.vitamin_c %></td>
        <td><%= fi.vitamin_d3 %></td>
        <td><%= fi.iron %></td>
        <td><%= fi.created_at.strftime('%d/%m/%Y %H:%M') %></td>
        <td><%= link_to 'show', recipe_path(fi) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/show.html.erb
<h1>Show Recipe <small>for <%= @data['date'] %></small></h1>
Vitamin C <%= @data['vitamin_c'] %> ( current level is <%= "#{@data['food_intake_vitamin_c']} - #{@data['activity_level_vitamin_c']} = #{@data['vitamin_c_diff']}" %> )
<br />
Vitamin D3 <%= @data['vitamin_d3'] %> ( current level is <%= "#{@data['food_intake_vitamin_d3']} - #{@data['activity_level_vitamin_d3']} = #{@data['vitamin_d3_diff']}" %> )
<br />
Vitamin Iron <%= @data['iron'] %> ( current level is <%= "#{@data['food_intake_iron']} - #{@data['activity_level_iron']} = #{@data['iron_diff']}" %> )

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>